In [1]:
import nashpy as nash
import numpy as np

In [8]:
issuer = np.array(
    [
        [-100, -100, 50, 50], 
        [-50, -50, 100, 100], 
        [0, 0, 10, 10], 
        [0, 0, 20, 20]
    ], 
dtype=np.int16)

rater = np.array(
    [
        [120, -100, 100, -50],
        [120, -50, 100, -100],
        [120, -100, 100, -50],
        [120, -50, 100, -100]
    ],
dtype=np.int16)

rating_game = nash.Game(issuer, rater)

In [9]:
rating_game

Bi matrix game with payoff matrices:

Row player:
[[-100 -100   50   50]
 [ -50  -50  100  100]
 [   0    0   10   10]
 [   0    0   20   20]]

Column player:
[[ 120 -100  100  -50]
 [ 120  -50  100 -100]
 [ 120 -100  100  -50]
 [ 120  -50  100 -100]]

In [10]:
eqs = rating_game.support_enumeration()

In [11]:
list(eqs)

/Users/chrible/work/projects/conference-simulation/simulation/.venv/lib/python3.8/site-packages/nashpy/algorithms/support_enumeration.py:260: RuntimeWarning: 
An even number of (2) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[(array([0., 0., 1., 0.]), array([1., 0., 0., 0.])),
 (array([0., 0., 0., 1.]), array([1., 0., 0., 0.]))]